#!/bin/sh
# shellcheck disable=SC2312
#
#   Demos many of dye's features.
#

set -eu

# shellcheck disable=SC1091
. ./dye.sh

dye setup

dye write "\

{{so}}|                         |{{end so}}
{{so}}|  dye's delightful demo  |{{end so}}
{{so}}|                         |{{end so}}

dye is a {{bold}}{{magenta}}portable{{reset
}} and {{bold}}{{cyan}}respectful{{reset
}} color library for shell scripts.

It's {{bold}}{{magenta}}portable{{reset
}} because it should run anywhere a POSIX shell exists.

It's {{bold}}{{cyan}}respectful{{reset
}} because it carefully determines whether to enable
color based on environment as well as user and developer preferences.
{{i}}(Try this demo again with NO_COLOR set!){{end i}}

{{yellow}}{{bold}}It has lots of colors and emphases:{{reset}}

It lets you use many {{red}}c{{yellow}}o{{green}}l{{cyan}}o{{blue
}}r{{magenta}}s{{reset}} as well as {{ul}}several{{end ul}}{{i
}}cool{{end i}} {{bold}}text{{reset}} {{so}}styles{{end so}}.

(And no, we didn't forget {{bg blue}}{{yellow}}background colors{{reset}}!)

{{dim}}You can even do dark {{red}}c{{yellow}}o{{green}}l{{cyan}}o{{blue
}}r{{magenta}}s {{white}}if you want...{{reset}}

{{yellow}}{{bold}}It supports {{ul}}256-color terminals{{end ul}}*:{{reset}}

"

print_range() (
	i="$1"
	end="$2"
	while [ "${i}" -le "${end}" ]; do
		dye fg "${i}"
		printf "%3s " "${i}"
		i=$((i + 1))
	done
	printf "\n"
)

print_range 0 15
printf "\n"

j=16
while [ "${j}" -le 231 ]; do
	print_range "${j}" $((j + 17))
	j=$((j + 36))
done
printf "\n"

j=34
while [ "${j}" -le 231 ]; do
	print_range "${j}" $((j + 17))
	j=$((j + 36))
done
printf "\n"

print_range 232 243
print_range 244 255

dye reset

dye write "\

          {{i
}}*Not what you expected? Check your TERM environment variable.{{end i}}

{{yellow}}{{bold}}It's super easy to use:{{reset}}

{{so}}                                                       {{end so}}
{{so}}  dye print 'Just like \{{red}}\{{bold}}this\{{reset}}!'  {{end so}}
{{so}}                                                       {{end so}}

You can embed it or source it, depending on your needs. You can also
just use parts of it, like the enable-color detection.

{{i}}And it's {{ul}}completely tested{{end ul}} with {{bold}}shellspec{{reset}}!

Get it at {{brightblue}}{{ul}}https://mattiebee.dev/dye{{reset}}.

"
